#!/bin/bash
# vim: fdm=marker

# System shortcuts {{{
alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../../'
alias nano='nano -HOSWimABC ~/.nano_backup -$'
alias open='xdg-open'
if [ -x /usr/bin/bat ]; then
	alias cat=bat
fi
if [ -x /usr/bin/batcat ]; then
	alias cat=batcat
fi


cols="--color=auto"
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	colored='grc'
else
	colored=''
fi

alias ping="$colored ping"
alias tracert='$colored traceroute'
alias traceroute='$colored traceroute'
alias mtr='$colored mtr'
alias man='$colored man'
alias grep='grep $cols'
alias fgrep='fgrep $cols'
alias egrep='egrep $cols'
alias dig='$colored dig'
alias ifconfig='$colored ifconfig'
alias ip='$colored ip'
alias iptables='sudo $colored iptables'
alias iptl='sudo $colored iptables -L -n -v --line-numbers'
# }}}
# ls & exa {{{
dirs1="--group-directories-first"
size="-r --sort=size"
extnsn="--sort=extension"
longpars="-lhF --time-style iso"

if which exa >/dev/null 2>&1; then
	version=$(exa --version | grep "^v.*$")
	version=${version:1:3}
	if [ "$version" = "0.1" ]; then
        longpars="$longpars --icons"
		longpars="$longpars --color-scale"
	fi
	modified="-rms modified"

    alias l="exa -F $dirs1"
    alias ls="exa -F $dirs1"
    alias ll="exa $longpars $dirs1"
    alias le="exa $extnsn $longpars"
    alias lsize="exa $size $longpars"
    alias lmod="exa $modified $longpars"

    alias la="exa -aF $dirs1"
    alias lal="exa -a $longpars $dirs1"
    alias lae="exa -a $extnsn $longpars"
    alias lasize="exa -a $size $longpars"
    alias lamod="exa -a $modified $longpars"
else
    modified="-t"

    alias l="ls -F $dirs1 $cols"
    alias ls="ls -F $dirs1 $cols"
    alias ll="ls $longpars $dirs1 $cols"
    alias le="ls $extnsn $longpars $cols"
    alias lsize="ls $size $longpars $cols"
    alias lmod="ls $modified $longpars $cols"

    alias la="ls -aF $dirs1 $cols"
    alias lal="ls -a $longpars $dirs1 $cols"
    alias lae="ls -a $extnsn $longpars $cols"
    alias lasize="ls -a $size $longpars $cols"
    alias lamod="ls -a $modified $longpars $cols"
fi
# }}}
# Bot commands {{{
alias Vol='bot vol'
alias Play='bot play'
alias Pause='bot pause'
alias Pp='bot pp'
alias pp='bot pp'
alias Next='bot next'
alias Prev='bot prev'
alias Mute='bot mute'
alias Unmute='bot unmute'
alias List='bot play list'
# }}}
# Tmux {{{
alias muxnew='tmux new-session'
alias muxdetach='tmux detach-client'
# }}}
# systemctl {{{
alias dereload='sudo systemctl daemon-reload'
alias udereload='systemctl --user daemon-reload'
# }}}
# git {{{
alias gs='git status'
alias gsu='git status -uno'
# }}}
# Applications {{{
alias update='sudo apt update'
alias tor='(/usr/sbin/tor &)'
alias mc='EDITOR=vim mc'
alias py3='python3'
alias ncmp-slave="ncmpcpp -c ~/.ncmpcpp/config-slave"
alias svim='vim -u $HOME/.SpaceVim/vimrc'
# }}}
# Personal {{{
#alias Повторить="$HOME/kimiside@gmail.com/Скрипты/repeating.py"
alias Повторитьбля="$HOME/bin/repeating_forgoten.sh"
alias Повторить="$HOME/bin/repeating.sh"
alias diary='vim ~/.Diary/$(date +"%Y")/$(date +"%Y-%m")/$(date +"%F_%H-%M").txt'
alias newdialog='vim ~/.imaginary_dialogs/$(date +"%Y-%m-%d").txt'
alias routine='cat >> /var/lib/kimifish/routinetasks.txt'
# }}}
# Other {{{
alias wifikey="sudo grep -r '^psk=' /etc/NetworkManager/system-connections/"
alias linein='pactl load-module module-loopback'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias bp="$HOME/bin/blueprox-switch.sh"
alias tada="paplay /usr/share/sounds/ubuntu/notifications/Soft\ delay.ogg"
alias НаТелефон='/home/kimifish/bin/kimibot/sendtophone.sh'
# }}}
